package com.smartbot.smartbot.exception;

public enum ErrorType {

  logical, business, REQUIRED_MISSING, INVALID_TYPE, INVALID_VALUE, INVALID_LENGTH, INVLID_OPERATION, INTERNAL_SERVER_ERROR, URL_NOT_FOUND, ACCESS_DENIED, USER_NOT_FOUND, USER_ALREADY_EXIST, RESOURCE_NOT_FOUND, RESOURCE_ALREADY_EXIST, INVALID_REQUEST_HEADER, INVALID_REQUEST
}